# Generated by Django 6.0.6 on 2026-06-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reposteria_app', '0002_categoria_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Imagen del Producto'),
        ),
    ]
