# Generated by Django 6.0.6 on 2026-06-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reposteria_app', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
    ]
