# Generated by Django 6.0.6 on 2026-06-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reposteria_app', '0005_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacado en Inicio'),
        ),
    ]
