# Generated by Django 6.0.5 on 2026-06-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reposteria_app', '0006_producto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(default=0, verbose_name='Descuento (%)'),
        ),
    ]
